controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
show_tour:
    path: /tour/{id}
    controller: App\Controller\AppController::showTour
