controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# show_tour:
#     path: /tour/{id}
#     controller: App\Controller\AppController::tour
home:
    path: /{_locale}
    controller: App\Controller\AppController::index
    requirements:
        _locale: en|fr


change_locale:
    path: /change-locale/{_locale}
    controller: App\Controller\LocaleController::changeLocale
    requirements:
        _locale: en|fr

